server:
  servlet:
    context-path: "/albot"
  port: 8181


spring:
  #   profiles: test
  #   name: test-YAML
  #   environment: dev
  datasource:
    platform: "postgres"
    url: jdbc:postgresql://localhost:5432/ventilator
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
logging:
  file: logs/ventilator-debug.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    io.albot: DEBUG
    org.hibernate: ERROR

sns_config:
  awsAccessKeyId: "AKIAXPEX6XFHKE2EGIP2"
  secretKey: "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"
  region: "us-east-2"

aws-s3-details:
  bucket: user-profiles-list

jwt_token:
  securityKey: "secret"
  #Token will expired after 60000 milliseconds
  tokenExpireTime: 300000
  region: "us-east-1"


