

server :
    servlet :
       context-path : "/albot"
    port : 8181

spring:
#   profiles: test
#   name: test-YAML
#   environment: dev
    data:
      cassandra:
           keyspace-name: "hospital"
#          cluster-name: "test-cluster"
           local-datacenter: "datacenter1"
           contact-points: 127.0.0.1
           port: 9042
#          username:
#          password
#             schema-action: CREATE_IF_NOT_EXISTS

logging:
#  file:
#    name: D:/logs/Content-OrchestrationService.log
#    pattern:
#      console: "%d %-5level %logger : %msg%n"
#      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
     org.springframework.web: DEBUG
     com.albot.contentorchestrationservice: DEBUG
     com.datastax.driver.core.QueryLogger.NORMAL: TRACE
     com.datastax.driver.core.QueryLogger.SLOW: TRACE

elastic_search:
  host: "localhost"
  schema: "http"
  port: 9200
  username: "elastic"
  password: "password"
  clustername: "dev_cluster"